### ISSUE TITLE
MarkdownLinkConceal can't work once EasySessionLoad

### ISSUE THREAD

**Issue by VimWei** [jamescherti/vim-easysession#1]
I have the following vimrc to conceal MarkdownLink. It can work before use vim-easysession.

1.  `vim-init\ftplugin\markdown.vim`:  `setlocal conceallevel=2`
2.  `vim-init\init\keymaps.vim`: 

```
augroup MarkdownLinkConceal
    autocmd!
    autocmd FileType markdown
        \ syn region markdownLink matchgroup=markdownLinkDelimiter
        \ start="(" end=")" keepend conceal contains=markdownUrl
    autocmd FileType markdown
        \ syn region markdownLinkText matchgroup=markdownLinkTextDelimiter
        \ start="!\=\[\%(\_[^][]*\%(\[\_[^][]*\]\_[^][]*\)*]\%( \=[[(]\)\)\@="
        \ end="\]\%( \=[[(]\)\@=" nextgroup=markdownLink,markdownId skipwhite
        \ contains=@markdownInline,markdownLineStart concealends
augroup END
```

However, once vim-easysession is enabled, the function to conceal markdown links stops working.

This is my vim-easysession setting:

```
    Plug 'jamescherti/vim-easysession'
    let g:easysession_auto_load = 1
    let g:easysession_auto_save = 1
```

I don't know if you have encountered a similar issue?

**Comment by VimWei** [comment]
If I disable vim-easysession plugin, and use `:mksession` and `:so`, the augroup MarkdownLinkConceal can work.

* My Environment:
    - Windows 10 Pro 22H2
    - gvim_9.1.0309_x64_signed.exe

**Comment by jamescherti** [comment]
Hello @VimWei ,

Thank you for reporting this issue.

Could you try the following:

1. Disable auto save and auto load in your vimrc:
```
Plug 'jamescherti/vim-easysession'
let g:easysession_auto_load = 0
let g:easysession_auto_save = 0
```

2. Restart Vim.

3. Save the session manually:
```
:EasySessionSave
```

4. Restart Vim

5. Then, load the session manually:
```
:EasySessionLoad
```

Is the function to conceal markdown links still working when you load the session manually?

**Comment by VimWei** [comment]
> Could you try the following

Result: the function to conceal markdown links can't work.

* More feedback:
1. Enable vim-easysession but disable auto save and auto load, and restart.  Open markdown file: **the function to conceal markdown links can work.**
2. `:EasySessionSave`
3. Restart Vim
4. open markdown file: **the function to conceal markdown links can work.**
5. `:EasySessionLoad`: **the function to conceal markdown links can‘t work.**

* Compare:
1. Enable vim-easysession but disable auto save and auto load, and restart.  Open markdown file: **the function to conceal markdown links can work.**
2. `:mssession ~/vimfiles/session/main.vim`
3. Restart Vim
4. open markdown file: **the function to conceal markdown links can work.**
5. `:so ~/vimfiles/session/main.vim` : **the function to conceal markdown links can work.**

* FYI: my vim-init  https://github.com/VimWei/vim-init

**Comment by jamescherti** [comment]
Vim Easysession uses `:mksession` and `:source`. The outcomes are expected to be identical. I am curious about the differences between the two session files Vim generated.

Would you be able to attach the `~/vimfiles/session/main.vim` file and the easysession file located in the directory `~/.vim_easysession/` to your comment so that I can compare them?

**Comment by VimWei** [comment]
1. Restart gvim.
2. Random open two files.
3. `:EasySessionSave`

[easysession.zip](https://github.com/jamescherti/vim-easysession/files/15055296/easysession.zip)

4. `mksession! ~/vimfiles/session/main.vim`

[mksession.zip](https://github.com/jamescherti/vim-easysession/files/15055297/mksession.zip)

**Comment by jamescherti** [comment]
I have just pushed a fix. Could you please try again with the latest version of EasySession from the main branch?

**Comment by VimWei** [comment]
1. Update and restart gvim:

```
    let g:easysession_auto_save = 1
    let g:easysession_auto_load = 1
```
2. Random open two files.

3. Result:  the function to conceal markdown links sometime can work, but sometime can't work. I haven't found a pattern.
Moreover, gVim always enters 'visual' mode, making it unusable.

**Comment by jamescherti** [comment]
What's in your `sessionoptions`?
```
:set sessionoptions?
```

**Comment by VimWei** [comment]
It remains at the default value:

`  sessionoptions=blank,buffers,curdir,folds,help,options,tabpages,winsize,terminal`

**Comment by jamescherti** [comment]
Does replacing it with the following fix the issue:
```
set sessionoptions=blank,curdir,folds,help,tabpages,unix,slash,winsize,terminal
```

(`sessionoptions` must be declared before loading easyssion.)

**Comment by VimWei** [comment]
After configuring sessionoptions, the following improvements were observed:
1. The problem where gVim constantly enters 'visual' mode and becomes unusable has been resolved.
2. However, the issue with concealing markdown links persists.

**Comment by jamescherti** [comment]
Good thing the first issue was fixed. I added the `sessionoptions` to the `README.md` file.

For `MarkdownLinkConceal`, try declaring it both before and after loading EasySession to see if it makes any difference.

**Comment by VimWei** [comment]
> For `MarkdownLinkConceal`, try declaring it both before and after loading EasySession to see if it makes any difference.

 * How?  I use command `:EasySessionLoad`.   
 Is it mean:

```
    " this is before
    let g:easysession_auto_save = 1
    let g:easysession_auto_load = 0
    set sessionoptions=blank,curdir,folds,help,tabpages,unix,slash,winsize
    " this is after
```

* More feedback: compare mksession and easysession

1. Config and restart gvim:

```
    Plug 'jamescherti/vim-easysession'
    let g:easysession_auto_save = 1
    let g:easysession_auto_load = 0
    set sessionoptions=blank,curdir,folds,help,tabpages,unix,slash,winsize
```

2. Open some files, and **use colorscheme A**.

3. `mksession! ~/vimfiles/session/main.vim `

4. Restart gvim.

Result: **gvim would change to colorscheme B**.   
FYI: https://github.com/VimWei/vim-init/blob/master/init/colorstyle.vim

5. `so ~/vimfiles/session/main.vim`

Result: gvim restore session, but **still use colorscheme B.**

6.  `:EasySessionLoad`

Result: gvim restore session, and **restore colorscheme to A**.

Does this feature affect the aforementioned issue?

**Comment by jamescherti** [comment]
For the color scheme issue, try again with the latest version of EasySession (from the main branch) with the following options:
```
let g:easysession_auto_load = 1
let g:easysession_auto_save = 1
let g:easysession_save_guifont = 0
let g:easysession_save_colorscheme = 0
```

**Comment by VimWei** [comment]
Great, all the issues have been resolved, include: MarkdownLinkConceal, colorscheme and accidentally entering visual mode.

I only made the following configurations, without setting sessionoptions, nor declaring MarkdownLinkConceal both before and after loading EasySession.

```
let g:easysession_auto_load = 1
let g:easysession_auto_save = 1
let g:easysession_save_guifont = 0
let g:easysession_save_colorscheme = 0
" set sessionoptions=blank,curdir,folds,help,tabpages,unix,slash,winsize
```

Thanks!

**Comment by jamescherti** [comment]
I'm glad to hear that everything is working smoothly now! If you have any more questions or need further assistance in the future, feel free to reach out.

I modified the default values of the following variables to provide the user with the flexibility to decide whether to save the color scheme and the GUI font:
```viml
" The new default values:
let g:easysession_save_guifont = 0
let g:easysession_save_colorscheme = 0
```
